server:
  port: 8080
spring:
  application:
    name: sbunittest
  datasource:
    url: jdbc:h2:file:~/sbunittest
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
  #   show-sql: true
  #   defer-datasource-initialization: true
  #   properties:
  #     hibernate:
  #       format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.kgisl.sbunittest: INFO

  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: 
    name: logs/sbunittest.log
